stages:
  - build
  - test
  - cleanup

variables:
  IMAGE_NAME: "simple-web-app"
  CONTAINER_NAME: "PythonApp"
  FULL_IMAGE_NAME: $IMAGE_NAME:$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA

default:
  tags:
    - my_first_runner
    
build_job:
  stage: build
  script: docker build -t $FULL_IMAGE_NAME . 

run_job:
  stage: build
  script: docker run -p 5000:5000 -d --name $CONTAINER_NAME $FULL_IMAGE_NAME

test-job:
  stage: test
  script: curl localhost:5000

cleanup_job:
  stage: cleanup
  script:
    - docker stop $CONTAINER_NAME
    - docker rm $CONTAIMER_NAME
    - docker rmi $FULL_IMAGE_NAME
    - docker system prune -f
  when: always
