variables:
  IMAGE_NAME: "simple-web-app"
  CONTAINER_NAME: "PythonApp"
  FULL_IMAGE_NAME: $IMAGE_NAME:$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA

default:
  tags:
    - my_first_runner
    
build-image:
  script: docker build -t $FULL_IMAGE_NAME . 

run-app:
  script: docker run -p 5000:5000 -d --name $CONTAINER_NAME $FULL_IMAGE_NAME

test-job:
  script: curl localhost:5000

cleanup:
  script:
    - docker rmi $FULL_IMAGE_NAME
    - docker system prune -f
  
